### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by akroii** [cliffparnitzky/TinyMceBundleAll#1]
I'm using Contao 4 Managed Edition (4.4.11) with PHP 7.1.8.
I just clicked on tiny-mce-bundle-all to install this extension.

**Output console:**
```
Using version ^2.10 for cliffparnitzky/tiny-mce-bundle-all
/Applications/MAMP/htdocs/xxxx/composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - contao/core 3.3.0 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.3.1 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.3.2 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.3.3 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.3.4 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.3.5 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.3.6 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.3.7 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.0 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.1 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.2 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.3 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.4 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.4.5 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.0 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.1 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.10 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.11 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.12 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.13 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.14 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.15 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.16 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.17 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.18 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.19 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.2 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.20 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.21 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.22 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.23 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.24 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.25 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.26 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.27 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.28 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.29 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.3 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.30 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.31 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.4 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.5 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.6 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.7 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.8 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - contao/core 3.5.9 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].
    - cliffparnitzky/tiny-mce-bundle-all 2.10.1 requires cliffparnitzky/tiny-mce-anchor ~1.1 -> no matching package found.
    - Installation request for contao/managed-edition No version set (parsed as 1.0.0) -> satisfiable by contao/managed-edition[No version set (parsed as 1.0.0)].
    - cliffparnitzky/tiny-mce-bundle-all 2.10.0 requires contao/core >=3.3.0,<3.6 -> satisfiable by contao/core[3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.3.5, 3.3.6, 3.3.7, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.5.0, 3.5.1, 3.5.10, 3.5.11, 3.5.12, 3.5.13, 3.5.14, 3.5.15, 3.5.16, 3.5.17, 3.5.18, 3.5.19, 3.5.2, 3.5.20, 3.5.21, 3.5.22, 3.5.23, 3.5.24, 3.5.25, 3.5.26, 3.5.27, 3.5.28, 3.5.29, 3.5.3, 3.5.30, 3.5.31, 3.5.4, 3.5.5, 3.5.6, 3.5.7, 3.5.8, 3.5.9].
    - Installation request for cliffparnitzky/tiny-mce-bundle-all ^2.10 -> satisfiable by cliffparnitzky/tiny-mce-bundle-all[2.10.0, 2.10.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
<warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>

Installation failed, reverting /Applications/MAMP/htdocs/xxxx/composer.json to its original content.
--------------------------------------------------------
Exception occured: Error: command exit code was 2
#0 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/Applications/M...')
#3 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/Applications/M...')
#4 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(875): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php(55): require('phar:///Applica...')
#12 {main}
Chained exception: Error: command exit code was 2
#0 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/Applications/M...')
#3 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/Applications/M...')
#4 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(240): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(875): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(215): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/vendor/symfony/console/Application.php(122): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php/api/console(83): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Applications/MAMP/htdocs/xxxx/web/contao-manager.phar.php(55): require('phar:///Applica...')
#12 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error
```

composer.json
```
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0+",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": "^5.6|^7.0",
        "alnv/prosearch": "^1.1",
        "bugbuster/contao-botstatistics-bundle": "^1.0",
        "christianbarkowsky/rel-canonical": "^3.3",
        "codefog/contao-bootstrap": "^1.0",
        "codefog/contao-news_categories": "^3.0",
        "contao-monitoring/bundle-all": "^1.4",
        "contao/calendar-bundle": "^4.4",
        "contao/comments-bundle": "^4.4",
        "contao/faq-bundle": "^4.4",
        "contao/listing-bundle": "^4.4.8",
        "contao/manager-bundle": "4.4.*",
        "contao/news-bundle": "^4.4",
        "derhaeuptling/contao-lazy-images": "^2.0",
        "derhaeuptling/contao-mobilecontent": "^2.2",
        "derhaeuptling/contao-seo-serp-preview": "^3.0",
        "fritzmg/contao-inherit-article": "^1.3",
        "fritzmg/contao-news-related": "^1.1",
        "fritzmg/contao-nivo-lightbox": "^1.3",
        "fritzmg/contao-swiper": "^0.3.2",
        "hofff/contao-opengraph": "^3.2",
        "hofff/contao-trueurl": "^2.3",
        "jrgregory/m17-sticky-backend-footer": "^2.0",
        "oneup/contao-mailchimp": "^4.0",
        "pdir/amphtml-bundle": "^0.1.7",
        "pdir/mobilede-bundle": "^1.0",
        "terminal42/notification_center": "^1.4"
    },
    "prefer-stable": true,
    "minimum-stability": "stable",
    "conflict": {
        "contao/core-bundle": "<4.4.8"
    },
    "config": {
        "component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}

```

**Comment by cliffparnitzky** [comment]
Hi, everything is right here. Currently there are only some plugins available for Contao 4.x (here is a list: https://gist.github.com/cliffparnitzky/f5693c4bcf756ee73e8bdc2a5d37aa3a).

The bundle_all is currently not installable for Contao 4.

At the moment I've no concrete plans for updating the other plugings.
